---
title: "R0_prueba"
author: "Christian Castro"
date: "31-08-2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

## R

```{r cars}
library(readxl)
# ageandheight <- read_excel("r0manual.xlsx") #Upload the data
# ageandheight <- read_excel("copiapo.xlsx") #Upload the data
ageandheight <- read_excel("lapintana.xlsx") #Upload the data
# ageandheight <- read_excel("puntaarenas.xlsx") #Upload the data
R0_v <- c()
comuna_v <- c()
codigo_comuna_v <- c()
a <- 0
s <- 0
s_v <- c()
y_bueno <- c()
# yy=ageandheight$Y
# xx=ageandheight$X
# eee <-summary(lm(yy ~ xx))$coefficients[2]
#lmHeight = lm(Y~X, data = ageandheight) #Create the linear regression
#eee <-lmHeight
# eee
# write.table(eee,'R0_panama_por_corr.csv', col.names=F, append=T, sep = ",")


m <- seq(2, 42)
    
    for (i in m)
    {        
         #xx <- ageandheight$X[1:i]
        xx <- ageandheight$X[i-1:i]

         #yy <- ageandheight$Y[1:i]
        yy <- ageandheight$Y[i-1:i]
        
        if(!is.null(yy)){
        estimacion.R0 = -summary(lm(yy ~ xx))$coefficients[2]
        R0_v[i] <- estimacion.R0
        comuna_v <- "comuna"
        # codigo_comuna_v <- codigo_comuna
        # fecha_v <- fecha
        # dia_v <- dia
        }
    }
    
    eee <- data.frame(comuna_v, R0_v )
    print(eee)
    
    write.table(
        eee,
        'R0.csv',
        col.names = F,
        append = T,
        sep = ","
    )
    
    R0_v <- c()
    comuna_v <- c()
    codigo_comuna_v <-  c()
    a <- 0
    s <- 0
    s_v <- c()
    y <- c()

```
Y y X de la regresion lineal

```{r}

income.graph <- ggplot(ageandheight, aes(x=X, y=Y))+geom_point()
income.graph <- income.graph + geom_smooth(method="lm", col="red", size = 0.5)
income.graph

```





