---
title: "obtenerlosr0masaltos"
author: "DataIntelligence"
date: "09-07-2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,fig.width=20, fig.height=12
)
```

```{r uno}
library(ggplot2)
library(janitor)
library(dplyr)
library(readxl)
library(tidyverse)
library(hrbrthemes)
library(kableExtra)
options(knitr.table.format = "html")
library(babynames)

library(viridis)
library(DT)
library(plotly)

# la siguiente linea impide el despliegue de advertencias en forma local:
options(warn = -1)

library(tidyverse)
library(gghighlight)
library(magrittr)
library(readr)
library(ape)
library(ggdendro)
library(rmarkdown)
library(ggplot2)
library(gganimate)
theme_set(theme_bw()) 

```
```{r dos}


# covid19 <- read_xlsx("C:/Users/usuario/Desktop/covid9j.xlsx")

covid19 <- read.csv("com_chile_R0.csv", row.names=NULL)
# head(covid19)

set_elegido <- c()
colnames(covid19)
cnames <- c("num", "comuna", "R_0")
colnames(covid19) <- cnames
colnames(covid19)

# eliminamos los registros que contenga como comuna Maipú
covid19 <- covid19 %>% filter(comuna != "Maipú") 

# obtenemos todos los registros que cumplan con la condicion
r0_masaltos <- filter(covid19, (R_0 > 3))
# r0_masaltos

    # obtenemos de forma unica las comunas que cumplen la condicion
    comunas_unicas <- r0_masaltos$comuna %>% unique()
    comunas_unicas
    longitud = length(comunas_unicas)
    longitud
    
    datos<-data.frame()     
    
    # Extraemos laslos registros que cumplen la condicion de pertenecer a las comunas unicas
    # y las vamos añadiendo abajo de un dataset
    for(t in 1:longitud)
    {    
        set_elegido <- covid19 %>% filter(comuna == comunas_unicas[t]) 
        # print(set_elegido)
        datos<-rbind(datos,set_elegido)
    }

# datos
   
```

```{r}
options(repr.plot.width = 1400, repr.plot.height = 8000)
uno <- ggplot(datos, aes(x=num, y=R_0, group = comuna, colour =comuna)) +
    geom_line()  +geom_hline(yintercept=1,  color = "red", size=1) +
    geom_point( size=1, shape=21, fill="white") +
    theme_minimal() + ggtitle("Covid-19: Comunas que superaron un R0 de 3 en algún momento de     la pandemia en Chile.")

png(filename = "1.png", width = 1000, height = 1000,
    pointsize = 12)
print(uno)
dev.off()
uno


# jpeg(filename = "1.jpeg",
#     width = 1000, height = 1000, units = "px", pointsize = 12,
#     quality = 5000)
#     print(uno)
#     dev.off()
#     uno
```
```{r}
tmp <- datos%>%mutate(comuna2=comuna)

dos<-tmp %>%
    ggplot( aes(x=num, y=R_0)) +
    geom_line()  +geom_hline(yintercept=1,  color = "red", size=1) +
    geom_line( data=tmp %>% dplyr::select(-comuna), aes(group=comuna2), color="grey", size=0.5, alpha=0.5) +
    geom_line( aes(color=comuna), color="#69b3a2", size=1.2 )+
    scale_color_viridis(discrete = TRUE) +
    theme_ipsum() +
    theme(
        legend.position="none",
        legend.title = element_text(color = "blue", size = 14),
        legend.text = element_text(color = "red", size = 10),
        plot.title = element_text(size=16),
        panel.grid = element_blank()
    ) +
    ggtitle("Covid-19: Comunas que superaron un R0 de 3 en algún momento de la pandemia en Chile.") +  
    facet_wrap(~comuna)

png(filename = "2.png", width = 1000, height = 1000,
    pointsize = 12)
print(dos)
dev.off()
dos
```

```{r}
tres <- datos %>%
  mutate( highlight=ifelse(comuna=="Providencia", "Providencia", "Other")) %>%
  ggplot( aes(x=num, y=R_0, group=comuna, color=highlight, size=highlight)) +
    geom_line() +
    scale_color_manual(values = c("#69b3a2", "lightgrey")) +

    scale_size_manual(values=c(2,0.5)) +

    theme(legend.position="none") +
    ggtitle("Covid-19: Comunas que superaron un R0 de 3 en algún momento de la pandemia en Chile.") +
    theme_ipsum() +
    geom_label( x=1990, y=55000, label="Amanda reached 3550\nbabies in 1970", size=4, color="#69b3a2") +
    theme(
      legend.position="none",
      plot.title = element_text(size=14)
)

png(filename = "3.png", width = 1000, height = 1000,
    pointsize = 12)
print(tres)
dev.off()
tres

```

```{r}
cuatro <- datos %>%
  ggplot( aes(x=num, y=R_0, group=comuna, color=comuna)) +
    geom_line() +
    scale_color_viridis(discrete = TRUE) +
    theme(
      legend.position="none",
      plot.title = element_text(10)
    ) +
    ggtitle("Covid-19: Comunas que superaron un R0 de 3 en algún momento de la pandemia en Chile.") +
    theme_ipsum()


png(filename = "4.png", width = 1000, height = 1000,
    pointsize = 12)
print(cuatro)
dev.off()
cuatro

```






