---
title: "R0: leer un xlsx desde github"
author: "DataIntelligence"
date: "22-06-2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE
)
```
Version final del R0
Se corrige erro cometido al no descontar de los susceptibles infectados y recuperados de forma permanente en cada t.

https://rpubs.com/chrimaho/GitHubAutomation
```{r uno}
library(knitr)
library(kableExtra)
library(janitor)
library(dplyr)
library(readxl)
library(xlsx)
# la siguiente linea impide el despliegue de advertencias en forma local:
options(warn = -1)
library(tidyverse)
library(gghighlight)
library(magrittr)
library(readr)
library(ape)
library(ggdendro)
library(rmarkdown)
library(ggplot2)
library(gganimate)
library(lubridate)
library("readxl")
library(httr)
theme_set(theme_bw()) 
```

```{r}

github_link <- "https://github.com/Sud-Austral/Datos_Panama/blob/master/datacovidpa/Localiza%20PN%20v1.xlsx?raw=true"
temp_file <- tempfile(fileext = ".xlsx")
req <- GET(github_link,
          # autenticamos si lo necesitásemos con GITHUB_PAT:
          # authenticate(Sys.getenv("GITHUB_PAT"), ""),
          # escribimos los resultados en el disco:
           write_disk(path = temp_file))
itoR0 <- readxl::read_excel(temp_file, col_names = TRUE, sheet = "TODO CORREGIMIENTO")

itoR0


itoR0 <- itoR0[3:nrow(itoR0), c(4, 7, 9, 12, 14 ,16, 30)]
names(itoR0)[1] <- "Codigo_corr"
names(itoR0)[2] <- "Corregimiento"
names(itoR0)[3] <- "Fecha"
names(itoR0)[4] <- "Casos"
names(itoR0)[5] <- "Fallecidos"
names(itoR0)[6] <- "Recuperados"
names(itoR0)[7] <- "Poblacion"
itoR0
# tab$Corregimiento

itoR0$"Codigo_corr" <- as.numeric(itoR0$"Codigo_corr") 
itoR0$"Fecha" <- as.numeric(itoR0$"Fecha") 
itoR0$"Casos" <- as.numeric(itoR0$"Casos") 
itoR0$"Casos"[is.na(itoR0$"Casos")] <- 0
itoR0$"Fallecidos" <- as.numeric(itoR0$"Fallecidos") 
itoR0$"Fallecidos"[is.na(itoR0$"Fallecidos")] <- 0
itoR0$"Recuperados" <- as.numeric(itoR0$"Recuperados") 
itoR0$"Recuperados"[is.na(itoR0$"Recuperados")] <- 0
itoR0$"Poblacion" <- as.numeric(itoR0$"Poblacion") 

itoR0 = itoR0[-1,]

head(itoR0, 20)

```


```{r dos}



# comuna_en_cuestion <-  itoR0
comuna_en_cuestion <-  itoR0 %>% filter(Corregimiento == "Alanje (Cabecera)")
head(comuna_en_cuestion, 20)

 
R0_v <- c()
comuna_v <- c()
codigo_comuna_v <- c()
a <- 0
s <- 0
s_v <- c()
y_bueno <- c()

#Fecha <- as.Date(comuna_en_cuestion$Fecha, origin = "1899-12-30")

```


```{r tres}  

ux <- unique(comuna_en_cuestion$"Codigo_corr")

for(t in ux)
{

    if (t != "No Informado")
    {
        comuna_en_cuestion = itoR0[itoR0$"Codigo_corr" == t, ]
        
        longitud = nrow(comuna_en_cuestion)
        comuna <- comuna_en_cuestion$Corregimiento
        codigo_comuna <- comuna_en_cuestion$"Codigo_corr"
        dia <- comuna_en_cuestion$"DIA"
        fecha <- comuna_en_cuestion$Fecha
        
        
        if (nrow(comuna_en_cuestion) != 0 &&
            (comuna_en_cuestion$"Poblacion" != 0))
        {
            population = as.numeric(comuna_en_cuestion$"Poblacion")
            
            infectados.por.dia =
                aggregate(comuna_en_cuestion$"Casos" ~
                              comuna_en_cuestion$Fecha,
                          FUN = sum)
            
            fallecidos.por.dia =
                aggregate(comuna_en_cuestion$"Fallecidos" ~
                              comuna_en_cuestion$Fecha,
                          FUN = sum)
            
            infectados.por.dia2 =
                infectados.por.dia[, 2] + fallecidos.por.dia[, 2]
            
            recuperados.por.dia =
                aggregate(comuna_en_cuestion$"Recuperados" ~
                              comuna_en_cuestion$Fecha,
                          FUN = sum)
            
            # susceptibles.por.dia debe ir acumulando
            
            susceptibles.por.dia = population - infectados.por.dia2 - recuperados.por.dia[, 2]
            
            
            # Creamos la tabla SIR:
            tabla.comuna =
                data.frame(
                    unique(comuna_en_cuestion$Fecha),
                    susceptibles.por.dia,
                    infectados.por.dia2,
                    recuperados.por.dia[, 2],
                    population
                )
           # tabla.comuna = tabla.comuna[-1,]
            names(tabla.comuna) =
                c("Fecha",
                  "Susceptibles",
                  "Infectados",
                  "Recuperados",
                  "Poblacion")
            
            
            
            x = tabla.comuna$Recuperados
            y = population * log(tabla.comuna$Susceptibles)

        }
    }
tabla.comuna
    # susceptibles.por.dia debe ir acumulando la resta de infectados
    for (t in 2:nrow(comuna_en_cuestion))
    {
        s <<- s + tabla.comuna$Infectados[t] + tabla.comuna$Recuperados[t]
        s_v[t] <- tabla.comuna$Poblacion - s
        y_bueno[t] = population * log(s_v[t])
    }

    dataf = data.frame(s_v, tabla.comuna$Infectados,  y_bueno, tabla.comuna$Recuperados)
    print(dataf)

    m <- seq(2, longitud)
    
    for (i in m)
    {
        xx <- tabla.comuna$Recuperados[1:i]
        yy <- y_bueno[1:i]
        estimacion.R0 = -summary(lm(yy ~ xx))$coefficients[2]
        R0_v[i] <- estimacion.R0
        comuna_v <- comuna
        codigo_comuna_v <- codigo_comuna
        fecha_v <- fecha
        dia_v <- dia
    }
    
 #    eee <-
 #        data.frame(comuna_v, R0_v, codigo_comuna_v,  fecha_v, dia_v, comuna_en_cuestion$"Casos", comuna_en_cuestion$"Fallecidos", comuna_en_cuestion$"Recuperados", 
 # comuna_en_cuestion$"Poblacion"                  )
 #    print(eee)
    
        eee <-
        data.frame(comuna_v, R0_v)
    print(eee)
    
    
    
    write.table(
        eee,
        'R0_panama_por_corr.csv',
        col.names = F,
        append = T,
        sep = ","
    )
    
    R0_v <- c()
    comuna_v <- c()
    codigo_comuna_v <-  c()
    a <- 0
    s <- 0
    s_v <- c()
    y_bueno <- c()
}

```
