---
title: "r0_movil"
author: "Christian Castro"
date: "22-06-2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE
)
```

```{r uno}
library(janitor)
library(dplyr)
library(readxl)
# la siguiente linea impide el despliegue de advertencias en forma local:
options(warn = -1)

library(tidyverse)
library(gghighlight)
library(magrittr)

library(readr)
library(ape)
library(ggdendro)
library(rmarkdown)

library(ggplot2)
library(gganimate)
theme_set(theme_bw())

# covid19cod_comun <-
#   read_xlsx(
#     "data_20_mayo_sec.xlsx"
#   )

covid19 <- read_xlsx("distritos_con_cod.xlsx")
covid19$Fecha <- excel_numeric_to_date(covid19$Fecha)

covid19$Fecha

# se declara el vector de R0
 a <- c()

  # Se selecciona un subset con el primer codigo de la comuna:
  # comuna_en_cuestion = covid19[covid19$Codigo_comuna == covid19cod_comun$Codigo_comuna[1], ]
  
# se selecciona la comuna de alto hospicio
  comuna_en_cuestion = covid19[covid19$Comuna == "Panamá", ]

  # se debe obtener el lugar de la primera y la ultima observacion
  # nrow entrega el numero de filas de un array

  
 longitud = nrow(comuna_en_cuestion)

  
      # comuna_en_cuestion = data.frame(comuna_en_cuestion2)
    comuna_en_cuestion = data.frame(comuna_en_cuestion)
    comuna_en_cuestion

population <- comuna_en_cuestion$Poblacion
    
    
    
    # Calculamos los infectados, los recuperados y los susceptibles por dias:
infectados.por.dia = aggregate(comuna_en_cuestion$Casos_Diarios ~ comuna_en_cuestion$Fecha, FUN = sum)
    
infectados.por.dia  

fallecidos.por.dia = aggregate(comuna_en_cuestion$Fallecidos_Diarios ~ comuna_en_cuestion$Fecha, FUN = sum)

fallecidos.por.dia

infectados.por.dia2 =infectados.por.dia[,2] + fallecidos.por.dia[,2]
    
infectados.por.dia2  

recuperados.por.dia = aggregate(comuna_en_cuestion$Recuperados_Diarios ~ comuna_en_cuestion$Fecha, FUN = sum)
    
recuperados.por.dia
    
susceptibles.por.dia = population - infectados.por.dia2 - recuperados.por.dia[,2]
susceptibles.por.dia
```

```{r ocho}

tabla.comuna = data.frame(unique(comuna_en_cuestion$Fecha), susceptibles.por.dia, infectados.por.dia2,recuperados.por.dia[,2])

names(tabla.comuna) = c("Fecha", "Susceptibles", "Infectados", "Recuperados")

x = tabla.comuna$Recuperados
y = population*log(tabla.comuna$Susceptibles)
summary(lm(y~x))

```



    


```{r dos}

  m <- seq(2, longitud)

 for(i in m) {

   xx<- x[1:i]
    yy<- y[1:i]
    estimacion.R0 = -summary(lm(yy ~ xx))$coefficients[2]

    a[i] <- estimacion.R0


    com <- comuna_en_cuestion$Comuna %>% unique()


    cat("longitud",longitud,"El R", com, "es", estimacion.R0, "\n")

 }

```

```{r tres}
x <-  1:longitud

eee <- data.frame(x,a)

eee

```

```{r cuatro}
p <- ggplot(
  eee,
  aes(x, a)
  ) +
  geom_line(colour="#000099") +
  labs(x = "Dia de la infección", y = "R_0") +
  theme(legend.position = "top")
p
p + geom_point(colour ="#CC6666") + transition_reveal(x)
```


```{r cinco}
t <- c()
  m <- seq(2, 5)
 for(i in m) {

   x<- x[1:i]
    y<- y[1:i]
    estimacion.R0 = -summary(lm(y ~ x))$coefficients[2]
    t[i] <- estimacion.R0


    com <- comuna_en_cuestion$Comuna %>% unique()
    cat("longitud",longitud,"El R", com, "es", estimacion.R0, "\n")
}


```


