---
title: "PCA sobre DMCS"
author: "DataIntelligence"
date: "07-08-2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("FactoMineR")
library("factoextra")
library(readxl)
library(XLConnect)
library("openxlsx")
library(httr)
library(xlsx)
library(readr)
options(warn=-1)
```

## Análisis de la delincuencia en Chile

Éste código permite extraer la información necesaria para realizar un análisis sobre un año específico de los DMCS. 

```{r}

url1 <- "https://github.com/Sud-Austral/Bases_de_Datos_DS/blob/master/DMCS/Tasa_casos_dmcs_mensual_2001_2017w.xlsx?raw=true"
p1f <- tempfile()
download.file(url1, p1f, mode = "wb")

p1 <- read_excel(path = p1f, sheet = 2)
p2 = p1[-c(1, 2),]
names(p2) <- p2[1,]
p2 <- p2[-1,]
p3 <- p2[p2$UN_ADMIN == "COMUNA", ]
myvars <- c("UNIDAD TERRITORIAL", "38353")
newdata <- p3[myvars]
rob_vio_int <- as.numeric(as.matrix(newdata)[,2])
summary(rob_vio_int)

p1 <- read_excel(path = p1f, sheet = 3)
p2 = p1[-c(1, 2),]
names(p2) <- p2[1,]
p2 <- p2[-1,]
p3 <- p2[p2$UN_ADMIN == "COMUNA", ]
myvars <- c("UNIDAD TERRITORIAL", "38353")
newdata <- p3[myvars]
rob_fuerza <- as.numeric(as.matrix(newdata)[,2])
summary(rob_fuerza)



function_delitos <- function(arg) {
    p1 <- read_excel(path = p1f, sheet = arg)
    p2 = p1[-c(1, 2),]
    invisible(capture.output( names(p2) <- p2[1,], file='NUL'))
    p2 <- p2[-1,]
    p3 <- p2[p2$UN_ADMIN == "COMUNA", ]
    myvars <- c("UNIDAD TERRITORIAL", "38353")
    newdata <- p3[myvars]
    rob_fuerza <- as.numeric(as.matrix(newdata)[,2])
    print(summary(rob_fuerza))
}

v <- seq(4, 10, 1)
for ( i in v) {
    function_delitos(i)
    experience = rob_fuerza
    cbind(rob_fuerza, experience)
}

rob_fuerza
```











