---
title: "Propagación del Covid-19 por Comuna en la Región de la Araucanía desde el inicio de la pandemia en Chile."
author: "DataIntelligence"
date: "23-06-2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
	
# Fuente:
# https://arcruz0.github.io/libroadp/mapas.html	

# Región de Ñuble
# Región del Bío-Bío
# Región de La Araucanía
# Región de Los Ríos
# Región de Los Lagos  
# Región de Aysén del Gral.Ibañez del Campo
# Región de Magallanes y Antártica Chilena	
)
```
```{r cuerpo, echo=FALSE, results='hide'}
library(rnaturalearth)
library(ggplot2)
library(reticulate)
library(knitr)
library(tidyverse)
library(gghighlight)
library(magrittr)
library(readxl)
library(readr)
library(ape)
library(ggdendro)
library(bookdown)
library(janitor)
require(rgdal)
require(ggplot2)
library(sf)
library(ggrepel)
library(gganimate)

shp_comunas_chile = st_read("C:/Users/usuario/Documents/GitHub/Analisis_covid19_con_R/proyecto_integrado/shapes_de_chile/comunas.shp") 
covid19 <- read_xlsx("C:/Users/usuario/Documents/GitHub/Analisis_covid19_con_R/proyecto_integrado/geo_Aypyt/Covid.xlsx")
covid19$Fecha <- excel_numeric_to_date(covid19$Fecha)
# Región del Libertador Bernardo O'Higgins                   
# Región del Maule
# Región de Ñuble
# Región del Bío-Bío
# Región de La Araucanía
# Región de Los Ríos
# Región de Los Lagos  
# Región de Aysén del Gral.Ibañez del Campo
# Región de Magallanes y Antártica Chilena

```
```{r cuerpoa, echo=FALSE}

shp_comunas_ayp = shp_comunas_chile %>% filter(Region == "Región de La Araucanía")

shp_comunas_ayp <-
        shp_comunas_ayp %>% mutate(
                centroid = map(geometry, st_centroid),
                coords = map(centroid,
                             st_coordinates),
                coords_x = map_dbl(coords, 1),
                coords_y = map_dbl(coords, 2)
        )

covid19_ayp = covid19[covid19$Region == "La Araucanía", ]
colnames(covid19_ayp)[3] <- "cod_comuna"
data_ayp <- left_join(covid19_ayp, shp_comunas_ayp, by = "cod_comuna")
# head(data_ayp, 100)
data_ayp <- st_as_sf(data_ayp)
```

### Casos Activos

```{r cuerpob, echo=FALSE}
g <- ggplot(data_ayp)+
    geom_sf(aes(fill=Casos_Activos))+
    scale_fill_gradient(low = "#56B1F7", high = "#132B43")+
    transition_manual(Fecha)+
    geom_text_repel(mapping = aes(coords_x, coords_y, label = Comuna.x), size = 3, min.segment.length = 0) +
    labs(subtitle = "Fecha de la pandemia en la Región de La Araucanía: {current_frame}")
    animate(g, fps = 3, width = 750, height = 450)
    anim_save("laara_casos.gif")
```

### Muertes

```{r cuerpoc, echo=FALSE}
a <- ggplot(data_ayp) +
    geom_sf(aes(fill = Muertes)) +
    scale_fill_gradient(low = "#f7c3c3", high = "#ff3030") +
    transition_manual(Fecha) +
    geom_text_repel(mapping = aes(coords_x, coords_y, label = Comuna.x), size = 3, min.segment.length = 0) +
    labs(subtitle = "Fecha de la pandemia en la Región de La Araucanía: {current_frame}")
    animate(a, fps = 3, width = 750, height = 450)
    anim_save("laara_muertes.gif")
```
