---
title: "Graficos del R0 sobre las comunas de Chile por zona"
author: "DataIntelligence"
date: "22-06-2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE
)
```
No aparece Chillan ni Chillan viejo!
```{r uno}
library(knitr)
library(kableExtra)
library(janitor)
library(dplyr)
library(readxl)
library(ggplot2)
library(gridExtra)
# la siguiente linea impide el despliegue de advertencias en forma local:
options(warn = -1)
library(scales)
library(tidyverse)
library(gghighlight)
library(magrittr)
library(readr)
library(ape)
library(ggdendro)
library(rmarkdown)
library(ggplot2)
library(gganimate)
library(ggthemes)
library(openxlsx)
theme_set(theme_bw()) 
```

```{r dos}
# options("encoding" = "UTF-8")
# covid19 <- read_xlsx("C:/Users/usuario/Desktop/covid9j.xlsx")

R0 <- read.csv("C:/Users/usuario/Documents/GitHub_Personal/Algoritmos_R_y_PowerBI/R_0/R0_en_Chile.csv")
# R0



# le asignammos nombres a las columnas:
names = c("index","comuna", "R0", "cod_comuna", "region", "fecha")
colnames(R0) = names
colnames(R0)

# R0

# R0$fecha=openxlsx::convertToDate(R0$fecha)
# R0

zona_norte <- R0[ which(
    ((R0$comuna == 'Alto Hospicio') |
    (R0$comuna == 'Antofagasta')|
    (R0$comuna == 'Arica')|
    (R0$comuna == 'Calama')|
    (R0$comuna == 'Iquique'))
    # desde el 15-04-2020
    & ((R0$fecha > 43936))),]
 zona_norte

zona_norte_chico <- R0[ which(
    ((R0$comuna == 'Coquimbo') |
    (R0$comuna == 'Diego de Almagro')|
    (R0$comuna == 'La Serena')|
    (R0$comuna == 'Ovalle')|
    (R0$comuna == 'Vallenar'))
    # 04-05-2020
    & ((R0$fecha > 43955))),]
 zona_norte_chico

zona_central <- R0[ which(
    ((R0$comuna == 'Quillota') |
    (R0$comuna == 'Rancagua')|
    (R0$comuna == 'San Fernando')|
    (R0$comuna == 'Valparaíso')|
    (R0$comuna == 'Viña del Mar'))
     # desde el 15-04-2020
    & ((R0$fecha > 43936))),]
 zona_central

zona_centro_sur <- R0[ which(
    ((R0$comuna == 'Curicó') |
    (R0$comuna == 'Linares')|
    (R0$comuna == 'Los Angeles')|
    (R0$comuna == 'Talca')|
    (R0$comuna == 'Talcahuano'))
     # desde el 15-04-2020
    & ((R0$fecha > 43936))),]
 zona_centro_sur

zona_sur_austral <- R0[ which(
    ((R0$comuna == 'Ancud') |
    (R0$comuna == 'Osorno')|
    (R0$comuna == 'Puerto Montt')|
    (R0$comuna == 'Punta Arenas')|
    (R0$comuna == 'Temuco')|
    (R0$comuna == 'Valdivia'))
     # desde el 15-04-2020
    & ((R0$fecha > 43936))),]
 zona_sur_austral

zona_prin_ciu_stgo <- R0[ which(
    ((R0$comuna == 'Estación Central') |
    (R0$comuna == 'Las Condes')|
    (R0$comuna == 'Maipú')|
    (R0$comuna == 'Puente Alto')|
    (R0$comuna == 'Santiago'))
     # desde el 15-04-2020
    & ((R0$fecha > 43936))),]
 zona_prin_ciu_stgo

zona_menores_R0 <- R0[ which(
    ((R0$comuna == 'Cañete') |
    (R0$comuna == 'Combarbalá')|
    (R0$comuna == 'Fresia')|
    (R0$comuna == 'Los Lagos')|
    (R0$comuna == 'San Pablo'))
    # 27-05-2020
    & ((R0$fecha > 43978))),]
 zona_menores_R0

class(R0$fecha)
  



  
  R0_1 <- ggplot(zona_norte, aes(as.Date(fecha,  origin='1970-01-01'), R0)) + geom_line(size = 1.5, aes(color = factor(comuna)))+ 
  theme_economist()+scale_colour_economist() +
#   scale_color_brewer(palette="Paired")+
# theme_minimal()+ theme(legend.position="top") +

    geom_text(x = 43937, y = 2.14, label = "2.11", size=7, color="red") +
    geom_text(x = 43945, y = 2.02, label = "1.99", size=7, color="red") +
    geom_text(x = 43958, y = 2.54, label = "2.49", size=7, color="red") +
    geom_text(x = 43950, y = 1.83, label = "1.8", size=7, color="red") +
    geom_text(x = 43968, y = 2.18, label = "2.15", size=7, color="red") +
    geom_text(x = 43973, y = 2.12, label = "2.07", size=7, color="red") +
    geom_text(x = 43979, y = 2.07, label = "2.02", size=7, color="red") +
    geom_text(x = 43983, y = 2.11, label = "2.06", size=7, color="red") +
    geom_text(x = 43997, y = 2.62, label = "2.58", size=7, color="red") +
    geom_text(x = 44004, y = 2.29, label = "2.25", size=7, color="red") +
    geom_text(x = 44020, y = 2.05, label = "2", size=7, color="red") +
    geom_text(x = 44029, y = 2.01, label = "1.97", size=7, color="red") +
    geom_text(x = 43939, y = 0.94, label = "0.97", size=7, color="red") +
    geom_text(x = 43949, y = 1.2, label = "1.23", size=7, color="red") +
    geom_text(x = 43963, y = 1.375, label = "1.41", size=7, color="red") +
    geom_text(x = 44034, y = 1.68, label = "1.68", size=7, color="red") +
    geom_text(x = 44034, y = 1.54, label = "1.54", size=7, color="red") +
    geom_text(x = 44034, y = 1.717, label = "1.71", size=7, color="red") +
    geom_text(x = 44034, y = 1.83, label = "1.83", size=7, color="red")  +
    geom_text(x = 43959, y = 1.13, label = "1.16", size=7, color="red") +
    geom_text(x = 43978, y = 1.61, label = "1.63", size=7, color="red") +
    geom_text(x = 43971 , y = 1.54, label = "1.57", size=7, color="red") +
    geom_text(x = 43992, y = 1.5, label = "1.52", size=7, color="red")+

  
labs(color = "Comunas") + ggtitle("Evolución diaria del Número Básico de Reproducción \n para las 5 Comunas principales de la Zona Norte de Chile \n desde el 15 de Abril al 20 de Julio del 2020") + xlab("DÍA") + ylab("Número Básico de Reproducción") +
    theme(plot.title = element_text(size = 28, face = "bold", hjust = 0.5),
    axis.title.x = element_text(size=22, face="bold", angle=0, hjust=1),
    axis.title.y = element_text(size=22, face="bold"),
    legend.text=element_text(size=22)) +
    theme(legend.title = element_text(size=22, face="bold"))+
    theme(text = element_text(size=20)) 

# + scale_x_date(labels = date_format("%m/%d")) +
#   theme(axis.text.fecha = element_text(angle=45))

png(filename = "R0_1.png", width = 1200, height = 1000,
    pointsize = 12)
print(R0_1)
dev.off()

###
# 
R0_2 <- ggplot(zona_norte_chico, aes(as.Date(fecha,  origin='1970-01-01'), R0)) + geom_line(size = 1.5, aes(color = factor(comuna)))+ 
  theme_economist()+scale_colour_economist() +

     geom_text(x =43959, y = 1.45 , label = "1.4 ", size=7, color="red") +
    geom_text(x = 43966, y = 1.66, label = "1.61", size=7, color="red") +
    geom_text(x = 43975, y = 2.09, label = "2.05", size=7, color="red") +
        geom_text(x = 43980, y = 2.66, label = "2.61", size=7, color="red") +
        geom_text(x = 43993, y = 1.98, label = "1.94", size=7, color="red") +
        geom_text(x = 43999, y = 1.95, label = "1.9", size=7, color="red") +
        geom_text(x = 44034, y = 0.98, label = "0.98", size=7, color="red") +
        geom_text(x = 44034, y = 1.32, label = "1.32", size=7, color="red") +
        geom_text(x = 44034, y = 1.47, label = "1.46", size=7, color="red") +
        geom_text(x = 44034, y = 1.56, label = "1.53", size=7, color="red") +
        geom_text(x = 44034, y = 1.421, label = "1.40", size=7, color="red") +
  
  
  
        geom_text(x = 43977, y = 1.038, label = "1.06", size=7, color="red") +
        geom_text(x = 43983, y = 1.043, label = "1.07", size=7, color="red") +
        geom_text(x = 43974, y = 1.32, label = "1.36", size=7, color="red") +
        geom_text(x = 43979, y = 1.37, label = "1.4", size=7, color="red") +
        geom_text(x = 43985, y = 1.38, label = "1.41", size=7, color="red") +
          geom_text(x = 43991, y = 1.49, label = "1.52", size=7, color="red") +
          geom_text(x = 43996, y = 1.58, label = "1.61", size=7, color="red") +
  
  

            geom_text(x = 43956, y = 0.51, label = "0.54", size=7, color="red") +

            geom_text(x = 43977, y = 0.71, label = "0.76", size=7, color="red") +
            geom_text(x = 43993, y = 0.88, label = "0.91", size=7, color="red") +

            geom_text(x = 44006, y = 0.88, label = "0.92", size=7, color="red") +
  
  
  
  
  
  
  
  
  

  
labs(color = "Comunas") + ggtitle("Evolución diaria del Número Básico de Reproducción \n para las 5 Comunas principales de la Zona Norte Chico de Chile \n desde el 4 de Mayo al 20 de Julio del 2020") + xlab("DÍA") + ylab("Número Básico de Reproducción") +
    theme(plot.title = element_text(size = 28, face = "bold", hjust = 0.5),
    axis.title.x = element_text(size=22, face="bold", angle=0, hjust=1),
    axis.title.y = element_text(size=22, face="bold"),
    legend.text=element_text(size=22)) +
    theme(legend.title = element_text(size=22, face="bold"))+
    theme(text = element_text(size=20)) 

# ggsave(R0_2,file="R0_2_ggsave.png") 

png(filename = "R0_2.png", width = 1200, height = 1000,
    pointsize = 12)
print(R0_2)
dev.off()

###

R0_3 <- ggplot(zona_central, aes(as.Date(as.Date(fecha,  origin='1970-01-01')), R0)) + geom_line(size = 1.5, aes(color = factor(comuna)))+  theme_economist()+scale_colour_economist() +

    geom_text(x = 43944, y = 1.49, label = "1.44", size=7, color="red") +
        geom_text(x = 43966, y = 2.66, label = "2.61", size=7, color="red") +
        geom_text(x = 43969, y = 2.57, label = "2.52", size=7, color="red") +
        geom_text(x = 43984, y = 2.27, label = "2.22", size=7, color="red") +
        geom_text(x = 43995, y = 2.46, label = "2.41", size=7, color="red") +
  
        geom_text(x = 44002, y = 2.89, label = "2.84", size=7, color="red") +
        geom_text(x = 43944, y = 0.73, label = "0.78", size=7, color="red") +
        geom_text(x = 43954, y = 0.63 , label = "0.68 ", size=7, color="red") +
        geom_text(x = 43972, y = 0.93, label = "0.98", size=7, color="red") +
        geom_text(x = 43981, y = 0.92, label = "0.97", size=7, color="red") +

        geom_text(x = 43986, y = 1.14, label = "1.19", size=7, color="red") +
        geom_text(x = 43994, y = 1.28, label = "1.33", size=7, color="red") +
        geom_text(x = 44032, y = 1.85 , label = "1.8 ", size=7, color="red") +
        geom_text(x = 44034, y = 1.79, label = "1.77", size=7, color="red") +
        geom_text(x = 44034, y = 1.725, label = "1.73", size=7, color="red") +


        geom_text(x = 44034, y = 1.55, label = "1.55", size=7, color="red") +

  
  
  


labs(color = "Comunas") + ggtitle("Evolución diaria del Número Básico de Reproducción \n para las 5 Comunas principales de la Zona Central de Chile \n desde el 15 de Abril al 20 de Julio del 2020") + xlab("DÍA") + ylab("Número Básico de Reproducción") +
    theme(plot.title = element_text(size = 28, face = "bold", hjust = 0.5),
    axis.title.x = element_text(size=22, face="bold", angle=0, hjust=1),
    axis.title.y = element_text(size=22, face="bold"),
    legend.text=element_text(size=22)) +
    theme(legend.title = element_text(size=22, face="bold"))+
    theme(text = element_text(size=20)) 
# + theme(axis.text.x=element_blank())

png(filename = "R0_3.png", width = 1200, height = 1000,
    pointsize = 12)
print(R0_3)
dev.off()

###

# 


  
  R0_4 <- ggplot(zona_centro_sur, aes(as.Date(as.Date(fecha,  origin='1970-01-01')), R0)) + geom_line(size = 1.5, aes(color = factor(comuna)))+  theme_economist()+scale_colour_economist() +
  
    geom_text(x = 43945, y = 1.37, label = "1.33", size=7, color="red") +
        geom_text(x = 43977, y = 2.42, label = "2.38", size=7, color="red") +
        geom_text(x = 43989, y = 2.11, label = "2.07", size=7, color="red") +
        geom_text(x = 43995, y = 1.87, label = "1.83", size=7, color="red") +
        geom_text(x = 44003, y = 1.94, label = "1.9", size=7, color="red") +
  
  
  
        geom_text(x = 43940, y = 0.5 , label = "0.54 ", size=7, color="red") +
        geom_text(x = 43949, y = 0.64, label = "0.68", size=7, color="red") +
        geom_text(x = 43991, y = 1.09 , label = "1.13 ", size=7, color="red") +
        geom_text(x = 44005, y = 1.16, label = "1.2", size=7, color="red") +
        geom_text(x = 44034, y = 1.69 , label = "1.67 ", size=7, color="red") +
  
  
  
        geom_text(x = 44034, y = 1.75 , label = "1.71 ", size=7, color="red") +
        geom_text(x = 44034, y = 1.65, label = "1.64", size=7, color="red") +
        geom_text(x = 44034, y = 1.5, label = "1.5", size=7, color="red") +
        geom_text(x = 44034, y = 1.611, label = "1.62", size=7, color="red") +
  
        geom_text(x = 43962, y = 1.07, label = "1.1", size=7, color="red") +
          geom_text(x = 43984, y = 1.63, label = "1.66", size=7, color="red") +
          geom_text(x = 44012, y = 1.59, label = "1.62", size=7, color="red") +
          geom_text(x = 43986, y = 1.49, label = "1.44", size=7, color="red") +
  
  
  

  



labs(color = "Comunas") + ggtitle("Evolución diaria del Número Básico de Reproducción \n para las 5 Comunas principales de la Zona Centro Sur de Chile \n desde el 15 de Abril al 20 de Julio del 2020") + xlab("DÍA") + ylab("Número Básico de Reproducción") +
    theme(plot.title = element_text(size = 28, face = "bold", hjust = 0.5),
    axis.title.x = element_text(size=22, face="bold", angle=0, hjust=1),
    axis.title.y = element_text(size=22, face="bold"),
    legend.text=element_text(size=22)) +
    theme(legend.title = element_text(size=22, face="bold"))+
    theme(text = element_text(size=20)) 

png(filename = "R0_4.png", width = 1200, height = 1000,
    pointsize = 12)
print(R0_4)
dev.off()

###

R0_5 <- ggplot(zona_sur_austral, aes(as.Date(as.Date(fecha,  origin='1970-01-01')), R0)) + geom_line(size = 1.5, aes(color = factor(comuna)))+ 
  
    theme_economist()+scale_colour_economist() +

    geom_text(x = 43942, y = 1.57, label = "1.54", size=7, color="red") +
    geom_text(x =  43964, y = 1.89, label = "1.86", size=7, color="red") +
      geom_text(x =  43984, y = 1.68, label = "1.65", size=7, color="red") +
      geom_text(x = 44029, y = 1.92, label = "1.89", size=7, color="red") +
      geom_text(x = 43940, y = 0.58, label = "0.61", size=7, color="red") +




      geom_text(x = 43956, y = 0.78, label = "0.81", size=7, color="red") +
        geom_text(x = 43977, y = 1.04, label = "1.07", size=7, color="red") +
        geom_text(x = 44007, y =1.03, label = "1.06", size=7, color="red") +
        geom_text(x = 44032, y = 1.54 , label = "1.57 ", size=7, color="red") +
        geom_text(x = 44032, y = 1.69, label = "1.71", size=7, color="red") +
  
  
  
  
  
        geom_text(x = 44032, y =1.05, label = "1.08", size=7, color="red") +
        geom_text(x = 44032, y = 1.29, label = "1.26", size=7, color="red") +
        geom_text(x = 44032, y = 1.38, label = "1.41", size=7, color="red") +
        geom_text(x = 44032 , y = 1.18, label = "1.21", size=7, color="red") +



labs(color = "Comunas") + ggtitle("Evolución diaria del Número Básico de Reproducción \n para las 5 Comunas principales de la Zona Sur Austral de Chile \n desde el 15 de Abril al 20 de Julio del 2020") + xlab("DÍA") + ylab("Número Básico de Reproducción") +
    theme(plot.title = element_text(size = 28, face = "bold", hjust = 0.5),
    axis.title.x = element_text(size=22, face="bold", angle=0, hjust=1),
    axis.title.y = element_text(size=22, face="bold"),
    legend.text=element_text(size=22)) +
    theme(legend.title = element_text(size=22, face="bold"))+
    theme(text = element_text(size=20)) 

png(filename = "R0_5.png", width = 1200, height = 1000,
    pointsize = 12)
print(R0_5)
dev.off()

###

R0_6 <- ggplot(zona_prin_ciu_stgo, aes(as.Date(as.Date(fecha,  origin='1970-01-01')), R0)) + geom_line(size = 1.5, aes(color = factor(comuna)))+
  theme_economist()+scale_colour_economist() +
  
  
  
    geom_text(x = 43937, y = 1.92, label = "1.89", size=7, color="red") +
    geom_text(x = 43953, y = 2.07, label = "2.04", size=7, color="red") +   
    geom_text(x = 43970, y = 2.36, label = "2.32", size=7, color="red") +  
    geom_text(x = 43966, y = 2.24, label = "2.21", size=7, color="red") +  
    geom_text(x = 43977, y = 2.17, label = "2.14", size=7, color="red") +

  
  
    geom_text(x = 43992, y = 2.45, label = "2.42", size=7, color="red") +
    geom_text(x = 43996, y = 2.41, label = "2.38", size=7, color="red") +   
    geom_text(x = 44034, y = 1.4, label = "1.39", size=7, color="red") +  
    geom_text(x = 44034, y = 1.24, label = "1.27", size=7, color="red") +  
    geom_text(x = 44034, y = 1.44, label = "1.41", size=7, color="red") +

  
  

    geom_text(x = 44034, y = 1.28, label = "1.28", size=7, color="red") +   
    geom_text(x = 43937, y = 0.95, label = "0.95", size=7, color="red") +  
    geom_text(x = 43970, y = 1.29, label = "1.32", size=7, color="red") +  
    geom_text(x = 43998, y = 1.21, label = "1.24", size=7, color="red") +

  
labs(color = "Comunas") + ggtitle("Evolución diaria del Número Básico de Reproducción \n para las 5 Comunas principales de la Región Metropolitana de Chile \n desde el 15 de Abril al 20 de Julio del 2020") + xlab("DÍA") + ylab("Número Básico de Reproducción") +
    theme(plot.title = element_text(size = 28, face = "bold", hjust = 0.5),
    axis.title.x = element_text(size=22, face="bold", angle=0, hjust=1),
    axis.title.y = element_text(size=22, face="bold"),
    legend.text=element_text(size=22)) +
    theme(legend.title = element_text(size=22, face="bold"))+
    theme(text = element_text(size=20)) 

png(filename = "R0_6.png", width = 1200, height = 1000,
    pointsize = 12)
print(R0_6)
dev.off()

###

R0_7 <- ggplot(zona_menores_R0, aes(as.Date(as.Date(fecha,  origin='1970-01-01')), R0)) + geom_line(size = 1.5, aes(color = factor(comuna)))+ theme_economist()+scale_colour_economist() +  

  
  
  
  
    geom_text(x = 43979, y = 1.84, label = "1.8", size=7, color="red") +  
     geom_text(x = 43980, y = 0.63, label = "0.67", size=7, color="red") + 
      geom_text(x = 43981, y = 0.98, label = "0.94", size=7, color="red") + 
      geom_text(x = 44020, y = 1.02, label = "0.97", size=7, color="red") + 

  
  
  
  
  
  
     geom_text(x = 43986, y = 0.54, label = "0.58", size=7, color="red") +  
     geom_text(x = 43999, y = 0.5, label = "0.54", size=7, color="red") + 
      geom_text(x = 43998, y = -0.67, label = "-0.63", size=7, color="red") + 
      geom_text(x = 44002, y = -0.2, label = "-0.17", size=7, color="red") + 
      geom_text(x = 44019, y = 0.79, label = "0.84", size=7, color="red") + 
  
  
  
  
  
  
     geom_text(x = 44029, y = 0.8, label = "0.85", size=7, color="red") +  
     geom_text(x = 44030, y = 1.14, label = "1.08", size=7, color="red") + 
      geom_text(x = 44033, y = 0.9, label = "0.89", size=7, color="red") + 
      geom_text(x = 44033, y = 1.06, label = "1.04", size=7, color="red") + 
      geom_text(x = 44033, y = 1.01, label = "0.98", size=7, color="red") + 
  
  
  
  
  
  
      geom_text(x = 44033, y = 0.84, label = "0.88", size=7, color="red") +  
     geom_text(x = 44033, y = 0.95, label = "0.96", size=7, color="red") + 

  
  
  
  
  

  
  
    
labs(color = "Comunas") + ggtitle("Evolución diaria del Número Básico de Reproducción \n para las 5 Comunas con los menores valores de R0 \n desde el 27 de Mayo al 20 de Julio del 2020") +
    xlab("DÍA") + ylab("Número Básico de Reproducción") +
    theme(plot.title = element_text(size = 28, face = "bold", hjust = 0.5),
    axis.title.x = element_text(size=22, face="bold", angle=0, hjust=1),
    axis.title.y = element_text(size=22, face="bold"),
    legend.text=element_text(size=22)) +
    theme(legend.title = element_text(size=22, face="bold"))+
    theme(text = element_text(size=20)) 

png(filename = "R0_7.png", width = 1200, height = 1000,
    pointsize = 12)
print(R0_7)
dev.off()

```

