---
title: "An치lisis geoespacial con R, de la epidemia Covid19 en Chile por Regi칩n a nivel comunal."
subtitle: "Regi칩n de Arica y Parinacota."
author: "DataIntelligence"
date: "21-07-2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
# Fuente:
# https://arcruz0.github.io/libroadp/mapas.html	
)
```

```{r cuerpo, echo=FALSE, results='hide'}
library(rnaturalearth)
library(ggplot2)
library(reticulate)
library(knitr)
library(tidyverse)
library(gghighlight)
library(magrittr)
library(readxl)
library(readr)
library(ape)
library(ggdendro)
library(bookdown)
library(janitor)
require(rgdal)
require(ggplot2)
library(sf)
library(ggrepel)
library(gganimate)
library(dplyr)
```

```{r cuerpo1, echo=FALSE}
# Cargamos la base de datos de los shapes:
shp_comunas_chile = st_read("C:/Users/usuario/Documents/GitHub_Personal/Bases_de_Datos_DS/shapes_de_chile/comunas.shp") 

# Leemos la base de datos de DataIntelligence y arreglamos el formato de la fecha:
covid19 <- read_xlsx("C:/Users/usuario/Documents/GitHub_Personal/Bases_de_Datos_DS/covid_23_julio.xlsx")

# No hay que hacer una transformacion en las fechas.
# Basta con que el formato de las fechas en el Excel sea: dd-mm-yyyy
```

```{r cuerpo2, echo=FALSE}

shp_comunas_por_region = shp_comunas_chile %>% filter(Region == "Regi칩n de Arica y Parinacota")

shp_comunas_por_region <- shp_comunas_por_region %>% mutate(
                centroid = map(geometry, st_centroid),
                coords = map(centroid, st_coordinates),
                coords_x = map_dbl(coords, 1),
                coords_y = map_dbl(coords, 2))

# Filtramos la base de datos:
covid19_region = covid19[covid19$Region == "Arica y Parinacota", ]
covid19_region = filter(covid19_region, covid19_region$'on-off' != 'OFF' & covid19_region$'on-off' != 'OUT TIME' & covid19_region$'Comuna' != 'No Informado')

# Renombramos columnas de la base de datos:
colnames(covid19_region)[3] <- "cod_comuna"
colnames(covid19_region)[9] <- "Casos_Activos"

data <- left_join(covid19_region, shp_comunas_por_region, by = "cod_comuna")

# Convert foreign object to an sf object
data <- st_as_sf(data)
```

### Casos Activos

```{r cuerpo3, echo=FALSE}
a <- ggplot(data) +
        geom_sf(aes(fill = Casos_Activos)) +
        scale_fill_gradient(low = "#56B1F7", high = "#132B43") +
        transition_manual(Fecha) +
        geom_text_repel(
                mapping = aes(coords_x, coords_y, label = Comuna.x),
                size = 4,
                min.segment.length = 0
        ) + labs(subtitle = "Fecha: {current_frame}")
animate(a, fps = 3, width = 750, height = 450)
anim_save("AP_1_casos_activos.gif")
```

### Muertes

```{r cuerpo4, echo=FALSE}
a <- ggplot(data) +
        geom_sf(aes(fill = Muertes)) +
        scale_fill_gradient(low = "#f7c3c3", high = "#ff3030") +
        transition_manual(Fecha) +
        geom_text_repel(
                mapping = aes(coords_x, coords_y, label = Comuna.x),
                size = 4,
                min.segment.length = 0
        ) + labs(subtitle = "Fecha: {current_frame}")
animate(a, fps = 3, width = 750, height = 450)
anim_save("AP_1_muertes.gif")
```



