---
title: "Análisis geoespacial con R, de la epidemia Covid19 en Chile por Región a nivel comunal."
# subtitle: "Casos Activos por 100.000 habitantes."
author: "DataIntelligence"
date: "21-05-2020"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
	
# Fuente:
# https://arcruz0.github.io/libroadp/mapas.html	
	
)
```
```{r cuerpo, echo=FALSE, results='hide'}
library(rnaturalearth)
library(ggplot2)
library(reticulate)
library(knitr)
library(tidyverse)
library(gghighlight)
library(magrittr)
library(readxl)
library(readr)
library(ape)
library(ggdendro)
library(bookdown)
library(janitor)
require(rgdal)
require(ggplot2)
library(sf)
library(ggrepel)
library(gganimate)
# Cargamos la base de datos de los shapes:
shp_comunas_chile = st_read("C:/Users/usuario/Documents/GitHub/Analisis_covid19_con_R/proyecto_integrado/shapes_de_chile/comunas.shp") 

# Leemos la base de datos de DataIntelligence y arreglamos el formato de la fecha:
covid19 <- read_xlsx("C:/Users/usuario/Documents/GitHub/Analisis_covid19_con_R/proyecto_integrado/geo_Aypyt/Covid.xlsx")
covid19$Fecha <- excel_numeric_to_date(covid19$Fecha)

################################################################################################

```


```{r cuerpoa, echo=FALSE}
################################################################################
################## Región de Arica y Parinacota ################################
################################################################################

# Cargamos la base de datos de los shapes:
shp_comunas_ayp = shp_comunas_chile %>% filter(Region == "Región de Tarapacá")

# Borrar una vez que se escriba:
# st_write(shp_comunas_ayp,"C:/Users/usuario/Documents/GitHub/Analisis_covid19_con_R/proyecto_integrado/geo_Aypyt/shapes/shp_comunas_ayp.shp")
# 
# shp_comunas_ayp = st_read(
#         "C:/Users/usuario/Documents/GitHub/Analisis_covid19_con_R/proyecto_integrado/geo_Aypyt/shapes/shp_comunas_ayp.shp")

shp_comunas_ayp <-
        shp_comunas_ayp %>% mutate(
                centroid = map(geometry, st_centroid),
                coords = map(centroid,
                             st_coordinates),
                coords_x = map_dbl(coords, 1),
                coords_y = map_dbl(coords,
                                   2)
        )

# Graficamos el shape:
# ggplot(shp_comunas_ayp) + geom_sf(aes(fill = Comuna)) +  guides(fill = "none")

# Extraemos los registros que contengan en el campo Region la palabra Región de Arica y Parinacota:
covid19_ayp = covid19[covid19$Region == "Tarapacá", ]
colnames(covid19_ayp)[3] <- "cod_comuna"
data_ayp <- left_join(covid19_ayp, shp_comunas_ayp, by = "cod_comuna")
# head(data_ayp, 100)
data_ayp <- st_as_sf(data_ayp)
```


### Casos Activos


```{r cuerpob, echo=FALSE}
a <- ggplot(data_ayp) +
        geom_sf(aes(fill = Casos_Activos)) +
        scale_fill_gradient(low = "#56B1F7", high = "#132B43") +
        transition_manual(Fecha) +
        geom_text_repel(
                mapping = aes(coords_x, coords_y, label = Comuna.x),
                size = 3,
                min.segment.length = 0
        ) +
        labs(subtitle = "Fecha de la pandemia en la Región de Tarapacá: {current_frame}")
#animate(a)
animate(a,
        fps = 3,
        width = 750,
        height = 450)
anim_save("tarap_casos.gif")
```

### Muertes

```{r cuerpoc, echo=FALSE}
a <- ggplot(data_ayp) +
        geom_sf(aes(fill = Muertes)) +
        scale_fill_gradient(low = "#f7c3c3", high = "#ff3030") +
        transition_manual(Fecha) +
        geom_text_repel(
                mapping = aes(coords_x, coords_y, label = Comuna.x),
                size = 3,
                min.segment.length = 0
        ) +
        labs(subtitle = "Fecha de la pandemia en la Región de Tarapacá: {current_frame}")
#animate(a)
animate(a,
        fps = 3,
        width = 750,
        height = 450)
anim_save("tarap_muertes.gif")
```
